FROM node:18.20.8-alpine

ARG S3ACCESSKEY=
ARG S3SECRETKEY=
ARG S3ENDPOINT=
ARG GITHASH=
ARG JSONDEBUG=false
ARG DEPLOY_ENV=green
ARG PORT=3001

WORKDIR /app

COPY --chown=1001:1001 . .
ENV NODE_OPTIONS=--max_old_space_size=16384
RUN npm install
ENV NODE_ENV=production
ENV GITHASH=${GITHASH}
ENV S3ACCESSKEY=${S3ACCESSKEY}
ENV S3SECRETKEY=${S3SECRETKEY}
ENV S3ENDPOINT=${S3ENDPOINT}
ENV JSONDEBUG=${JSONDEBUG}
RUN npm run build

COPY --chown=1001:1001 .next .next

ENV DEPLOY_VERSION=${DEPLOY_ENV}
ENV GITHASH=${GITHASH}
ENV S3ACCESSKEY=${S3ACCESSKEY}
ENV S3SECRETKEY=${S3SECRETKEY}
ENV S3ENDPOINT=${S3ENDPOINT}
ENV JSONDEBUG=${JSONDEBUG}
ENV NODE_ENV=production

EXPOSE ${PORT}

USER node

CMD [ "npm", "run", "start-${DEPLOY_VERSION}" ]