name: Update server data
on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: "server-data"
    cancel-in-progress: false

jobs:
    update-data:
        runs-on: ubuntu-latest
        env:
            S3ENDPOINT: ${{ secrets.S3ENDPOINT }}
            S3ACCESSKEY: ${{ secrets.S3ACCESSKEY }}
            S3SECRETKEY: ${{ secrets.S3SECRETKEY }}
            CACHEFOLDER: ${{ secrets.CACHE_FOLDER }}
        steps:
            - name: Update git on server
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  envs: S3ENDPOINT,S3ACCESSKEY,S3SECRETKEY
                  script: |
                      cd /hotelroot/manifest-report-site
                      git fetch
                      git pull origin main
                      npm install
                      npm run build
                      systemctl restart manifest-report-site
